import { Helmet } from "react-helmet-async";

import { SITE_NAME } from "@/lib/constants";
import { META_ABOUT_US_DESC, META_ABOUT_US_TITLE } from "@/lib/metaTags";

import logo from "@/assets/bronflix-text.png";
import Heading from "@/components/ui/Heading";
import ContentWall from "@/components/ui/ContentWall";

function AboutUs() {
  // Returned JSX
  return (
    <>
      {/* Meta data */}
      <Helmet>
        <title>{META_ABOUT_US_TITLE}</title>
        <meta name="description" content={META_ABOUT_US_DESC} />
        <meta name="robots" content="noindex,nofollow" />
      </Helmet>

      {/* Content */}
      <section>
        <Heading>About Us</Heading>
        <ContentWall>
          <img
            src={logo}
            width={750}
            alt={SITE_NAME}
            title={`${SITE_NAME} logo`}
          />
          <p>
            We're excited to present our latest project, {SITE_NAME}, a
            movie-based web application created with love for the movie
            industry.
          </p>

          <Heading as="h2">Project Purpose</Heading>
          <p>
            {SITE_NAME} was created as a portfolio project to showcase my skills
            while combining my love for movies with modern web development.
            Instead of going down the usual path of creating simple apps like
            calculators or clones, I wanted to craft something that reflects my
            passion and stands out with a unique theme.
          </p>
          <p>
            The goal was to build a dynamic movie platform with a sleek design
            and a great user experience, using the latest technologies and
            industry best practices. Through this project, I aimed to push my
            limits as a developer while delivering something both functional and
            engaging for movie enthusiasts.
          </p>
          <p>
            This project is a solo endeavor, designed to demonstrate my
            abilities in React, responsive design, and API integration. It also
            highlights my commitment to building clean, user-focused websites
            that provide real value to users.
          </p>

          <Heading as="h3">Technology Stack</Heading>
          <p>
            {SITE_NAME} is built with a modern and robust tech stack, combining
            powerful frameworks and tools to deliver an exceptional user
            experience. The project leverages industry-standard technologies to
            ensure scalability, type safety, and smooth performance throughout.
            From dynamic data handling to responsive design, every part of
            {SITE_NAME} is crafted with the latest web development practices in
            mind.
          </p>
          <p>
            By focusing on clean, efficient code and cutting-edge tools,
            {SITE_NAME} provides a seamless, engaging platform for users to
            explore movies, shows, and actors with ease and enjoyment.
          </p>

          <Heading as="h3">Usage and Ownership</Heading>
          <p>
            {SITE_NAME} is created purely for portfolio purposes and is not
            intended for commercial use. All movie-related data is sourced from
            the TMDB API, and any trademarks or logos used in the app belong to
            their respective owners.
          </p>
          <p>
            Content in {SITE_NAME} is generated by me. Any resemblance to
            real-world entities is purely coincidental, and some of the content
            may not be fully accurate due to its AI-generated nature.
          </p>

          <Heading as="h3">Accessing the Project</Heading>
          <p>
            {SITE_NAME} is hosted on GitHub and is available for everyone to
            explore. Feel free to{" "}
            <a href="https://github.com/vsbron/bronflix__react" target="_blank">
              visit
            </a>{" "}
            the repository and check out the code!
          </p>

          <Heading as="h3">Acknowledgments</Heading>
          <p>
            Special thanks go to Maria B. - For her general help throughout the
            project.
            <br />
            And of course, thanks to my family and friends for their support
            throughout the development process!
          </p>
          <hr />
          <p>
            Thank you for taking the time to visit {SITE_NAME}. We hope you
            enjoy exploring movies and discovering new content!
          </p>
        </ContentWall>
      </section>
    </>
  );
}

export default AboutUs;
